namespace TauriApiWrapper.Enums
{
    public enum AchievementCriteriaType
    {
        Undefined = -1,
        KillCreature = 0,
        WinBg = 1,
        ReachSkillLevel = 7,
        CompleteAchievement = 8,
        CompleteQuestCount = 9,
        CompleteDailyQuestDaily = 10,
        CompleteQuestsInZone = 11,
        DamageDone = 13,
        CompleteDailyQuest = 14,
        CompleteQuest = 27,
        BeSpellTarget = 28,
        CastSpell = 29,
        HonorableKill = 35,
        OwnItem = 36,
        WinRatedArena = 37,
        UseItem = 41,
        LootItem = 42,
        ExploreArea = 43,
        BuyBankSlot = 45,
        GainReputation = 46,
        GainExaltedReputation = 47,
        EquipEpicItem = 49,
        HKClass = 52,
        HKRace = 53,
        DoEmote = 54,
        GetKillingBlows = 56,
        MoneyFromQuestReward = 62,
        LootMoney = 67,
        UseGameobject = 68,
        BeSpellTarget2 = 69,
        SpecialPvpKill = 70,
        FishInGameobject = 72,
        LearnSkillLineSpell = 75,
        LootType = 109,
        EarnHonorableKill = 113,
        UseLfdToGroupWithPlayers = 119
    }
}